### ISSUE TITLE
username without the @domain.com

### ISSUE THREAD

**Issue by wesyah234** [dthree/addict#11]
I'm trying to authenticate a user named "username" however it seems this system is adding on the @domain.edu extension, and then failing... 

In the API tester web app, I only typed in username, but it is using username@domain.edu...

AUTH USER username@domain.edu password
BACK FROM AUTH { InvalidCredentialsError: InvalidCredentialsError
    at messageCallback (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1419:45)
    at Parser.onMessage (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at Parser.write (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at Socket.onData (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
  lde_message: '80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1\u0000',
  lde_dn: null } false

**Comment by dthree** [comment]
What's the full DN of the user? These usually have the FQDN appended to it, so addict does it by default.

**Comment by wesyah234** [comment]
I don't know a lot about AD (which is why I'm interested in REST web interface to it :) )... but what I can tell you is that we have a previous project that was able to connect to our system with the following nodejs code:

and this connection was able to validate people's passwords which is basically all I would need a REST interface to do.

var restify = require('restify');
var ActiveDirectory = require('activedirectory');
var config = {url: 'ldap://ourldapserver.net',
  baseDN: 'DC=mcwcorp,DC=net',
  username: 'xxxxxx',
  password: 'xxxxxxx'
}
var ad = new ActiveDirectory(config);
var server = restify.createServer();
