### ISSUE TITLE
Is the project being maintained anymore?

### ISSUE THREAD

**Issue by RangaSamdurala** [dthree/addict#35]
Hello
Is this project being maintained anymore? I see questions not answered for a while?

**Comment by RangaSamdurala** [comment]
I see the following error while trying to get a user, what could be the problem?

NOTE: I have replaced user name and domain name with placeholders.

Addict: user [user-name]
{ ReferralError: 0000202B: RefErr: DSID-0310082F, data 0, 1 access points
	ref 1: '[domain-name]'

    at messageCallback (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1419:45)
    at Parser.onMessage (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1089:14)
    at Parser.emit (events.js:182:13)
    at Parser.write (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at Socket.onData (/usr/local/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1076:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  lde_message:
   '0000202B: RefErr: DSID-0310082F, data 0, 1 access points\n\tref 1: \'[domain-name]\'\n\u0000',
  lde_dn: null }
Addict:
