### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by ajonp** [dthree/addict#5]
Do you need admin account just for login?
```
/usr/local/lib/node_modules/addict-api/node_modules/ad/src/user.js:27
	async getAllUsers(opts) {
	      ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/addict-api/node_modules/ad/index.js:5:8)
```

**Comment by dthree** [comment]
Yes, that's the idea. But I think your error is that you're running an older version of Node. Try Node 7.6 or higher.

**Comment by ajonp** [comment]
Upgraded node and everything looks good. I do wish we could use a normal user for the get operations though. In our company we all are allowed query rights.
![image](https://user-images.githubusercontent.com/3102249/28952463-437fcb02-789f-11e7-9e9b-815d4fb23c64.png)

**Comment by dthree** [comment]
Hmmmm okay. Let me see if I can work this!
