### ISSUE TITLE
Traceback when calling "addict --help"

### ISSUE THREAD

**Issue by spaceone** [dthree/addict#9]
```
$ addict --help
/usr/local/lib/node_modules/addict/index.js:25
const init = (args) => {
                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/addict/bin/index.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by dthree** [comment]
Hey.

You need to be running at least Node 7.6 or higher to support this app. Upgrade and try again.
